/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "sczqurjsiiaopszmuaof"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNjenF1cmpzaWlhb3Bzem11YW9mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNzg4MzAsImV4cCI6MjA3Mjc1NDgzMH0.RWYaDcMwaiUBosKY-b6C8JdU45xAXzDtw-TjPShIRGk"